# Generated by Django 3.2.7 on 2021-11-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
